const LOADING_PHOTOS_LIST = "LOADING_PHOTOS_LIST"
const LOADING_PHOTOS_LIST_SUCCESS = "LOADING_PHOTOS_LIST_SUCCESS"
const LOADING_PHOTOS_LIST_FAILED = "LOADING_PHOTOS_LIST_FAILED"

const SEARCH_LOADING_PHOTOS_LIST = "SEARCH_LOADING_PHOTOS_LIST";
const SEARCH_LOADING_PHOTOS_LIST_SUCCESS = "SEARCH_LOADING_PHOTOS_LIST_SUCCESS";
const SEARCH_LOADING_PHOTOS_LIST_FAILED = "SEARCH_LOADING_PHOTOS_LIST_FAILED";

const SEARCH_LOADING_COLLECTIONS_LIST = "SEARCH_LOADING_COLLECTIONS_LIST";
const SEARCH_LOADING_COLLECTIONS_LIST_SUCCESS = "SEARCH_LOADING_COLLECTIONS_LIST_SUCCESS";
const SEARCH_LOADING_COLLECTIONS_LIST_FAILED = "SEARCH_LOADING_COLLECTIONS_LIST_FAILED";

const SEARCH_LOADING_USERS_LIST = "SEARCH_LOADING_USERS_LIST";
const SEARCH_LOADING_USERS_LIST_SUCCESS = "SEARCH_LOADING_USERS_LIST_SUCCESS";
const SEARCH_LOADING_USERS_LIST_FAILED = "SEARCH_LOADING_USERS_LIST_FAILED";

const ORDER_BY_LATEST = "latest";
const ORDER_BY_OLDEST = "oldest";
const ORDER_BY_POPULAR = "popular";

const LOAD_PHOTO_SUCCESS = "LOAD_PHOTO_SUCCESS"
const LOAD_PHOTO_FAILED = "LOAD_PHOTO_FAILED"
const HIDE_MODAL_DETAIL_PHOTO = "HIDE_MODAL_DETAIL_PHOTO"

const LIKE_PHOTO_SUCCESS = "LIKE_PHOTO_SUCCESS"
const LIKE_PHOTO_FAILED = "LIKE_PHOTO_FAILED"

const UNLIKE_PHOTO_SUCCESS = "UNLIKE_PHOTO_SUCCESS"
const UNLIKE_PHOTO_FAILED = "UNLIKE_PHOTO_FAILED"

const DOWNLOAD_PHOTO_SUCCESS = "DOWNLOAD_PHOTO_SUCCESS"
const DOWNLOAD_PHOTO_FAILED = "DOWNLOAD_PHOTO_FAILED"


const INPUT_CHANGE = 'INPUT_CHANGE'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'

const UNSPLASH_SCOPE = [
    "public",
    "read_user",
    "write_user",
    "read_photos",
    "write_photos",
    "write_likes",
    "write_followers",
    "write_collections",
    "read_collections",
]

export {
    LOADING_PHOTOS_LIST,
    LOADING_PHOTOS_LIST_SUCCESS,
    LOADING_PHOTOS_LIST_FAILED,
    SEARCH_LOADING_PHOTOS_LIST,
    SEARCH_LOADING_PHOTOS_LIST_SUCCESS,
    SEARCH_LOADING_PHOTOS_LIST_FAILED,
    SEARCH_LOADING_COLLECTIONS_LIST,
    SEARCH_LOADING_COLLECTIONS_LIST_SUCCESS,
    SEARCH_LOADING_COLLECTIONS_LIST_FAILED,
    SEARCH_LOADING_USERS_LIST,
    SEARCH_LOADING_USERS_LIST_SUCCESS,
    SEARCH_LOADING_USERS_LIST_FAILED,
    LOAD_PHOTO_SUCCESS,
    LOAD_PHOTO_FAILED,
    HIDE_MODAL_DETAIL_PHOTO,
    LIKE_PHOTO_SUCCESS,
    LIKE_PHOTO_FAILED,
    UNLIKE_PHOTO_SUCCESS,
    UNLIKE_PHOTO_FAILED,
    DOWNLOAD_PHOTO_SUCCESS,
    DOWNLOAD_PHOTO_FAILED,
    INPUT_CHANGE,
    LOGIN,
    LOGOUT,
    ORDER_BY_LATEST,
    ORDER_BY_OLDEST,
    ORDER_BY_POPULAR,
    UNSPLASH_SCOPE
};
